[package]
name = "nuzlolcke"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
futures = "0.3.31"
riven = "2.56.0"
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.16"
